export const BRAND = {
  name: 'Agrivo',
  tagline: 'Marketplace Global de Servicios Agrícolas',
  description: 'Conectamos agricultores con profesionales del campo en todo el mundo',
};

export const COUNTRIES = [
  { name: 'España', code: 'ES', flag: 'https://flagcdn.com/w40/es.png' },
  { name: 'Brasil', code: 'BR', flag: 'https://flagcdn.com/w40/br.png' },
  { name: 'Argentina', code: 'AR', flag: 'https://flagcdn.com/w40/ar.png' },
  { name: 'USA', code: 'US', flag: 'https://flagcdn.com/w40/us.png' },
  { name: 'Portugal', code: 'PT', flag: 'https://flagcdn.com/w40/pt.png' },
  { name: 'France', code: 'FR', flag: 'https://flagcdn.com/w40/fr.png' },
  { name: 'India', code: 'IN', flag: 'https://flagcdn.com/w40/in.png' },
  { name: 'Australia', code: 'AU', flag: 'https://flagcdn.com/w40/au.png' },
  { name: 'Україна', code: 'UA', flag: 'https://flagcdn.com/w40/ua.png' },
  { name: 'México', code: 'MX', flag: 'https://flagcdn.com/w40/mx.png' },
];

export const CATEGORIES = [
  { id: 'drones', name: 'Drones Agrícolas', icon: '🛸', description: 'Fumigación, mapeo y monitoreo con drones' },
  { id: 'cosecha', name: 'Cosecha', icon: '🌾', description: 'Servicios de recolección y cosecha mecanizada' },
  { id: 'poda', name: 'Poda', icon: '✂️', description: 'Poda de árboles frutales y viñedos' },
  { id: 'arado', name: 'Arado', icon: '🚜', description: 'Preparación y labranza del suelo' },
  { id: 'siembra', name: 'Siembra', icon: '🌱', description: 'Siembra directa y convencional' },
  { id: 'riego', name: 'Riego', icon: '💧', description: 'Instalación y mantenimiento de sistemas de riego' },
  { id: 'fumigacion', name: 'Fumigación', icon: '🧪', description: 'Aplicación terrestre de fitosanitarios' },
  { id: 'analisis', name: 'Análisis de Suelo', icon: '🔬', description: 'Estudios y análisis de fertilidad' },
  { id: 'topografia', name: 'Topografía', icon: '📐', description: 'Relevamiento y nivelación de terrenos' },
  { id: 'ganaderia', name: 'Ganadería', icon: '🐄', description: 'Servicios veterinarios y manejo de ganado' },
  { id: 'consultoria', name: 'Consultoría', icon: '📊', description: 'Asesoramiento agronómico profesional' },
  { id: 'transporte', name: 'Transporte', icon: '🚛', description: 'Logística y transporte de granos' },
];

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: 'Gratis',
    description: 'Para empezar a explorar la plataforma',
    features: [
      'Publicar hasta 3 trabajos/mes',
      'Recibir hasta 5 ofertas por trabajo',
      'Perfil profesional básico',
      'Acceso al directorio',
      'Soporte por email',
    ],
    cta: 'Comenzar Gratis',
    popular: false,
  },
  {
    id: 'pro',
    name: 'Profesional',
    price: 19,
    period: '/mes',
    description: 'Para profesionales que quieren destacar',
    features: [
      'Todo lo de Free',
      'KYC completo verificado',
      'Insignia Verificado ✓',
      'Pujas ilimitadas',
      'Ranking priorizado en búsquedas',
      'Reseñas verificadas',
    ],
    cta: 'Suscribirse',
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Empresa',
    price: 29,
    period: '/mes',
    description: 'Para profesionales top y empresas',
    features: [
      'Todo lo de Verificado',
      'Destacado en portada',
      'Insignia Top Pro ⭐',
      'Radio ampliado de visibilidad',
      'Panel de analíticas',
      'Soporte prioritario',
    ],
    cta: 'Ser Top Pro',
    popular: false,
  },
];

// Seed professionals for initial display - these will be replaced as real users sign up
export const SEED_PROFESSIONALS = [
  {
    id: 'seed-1',
    display_name: 'Carlos Mendoza',
    country: 'Argentina',
    specialty: 'Drones Agrícolas',
    description: 'Piloto certificado con 5 años de experiencia en fumigación aérea con drones DJI Agras. Más de 10.000 hectáreas tratadas.',
    rating: 4.9,
    jobs_completed: 87,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-2',
    display_name: 'María García López',
    country: 'España',
    specialty: 'Poda',
    description: 'Especialista en poda de viñedos y olivos en la región de La Rioja. Técnica certificada en viticultura.',
    rating: 4.8,
    jobs_completed: 124,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-3',
    display_name: 'João Silva',
    country: 'Brasil',
    specialty: 'Cosecha',
    description: 'Operador de cosechadoras John Deere y Case IH. Experiencia en soja, maíz y algodón en Mato Grosso.',
    rating: 4.7,
    jobs_completed: 56,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-4',
    display_name: 'Pierre Dubois',
    country: 'France',
    specialty: 'Análisis de Suelo',
    description: 'Ingeniero agrónomo especializado en análisis de fertilidad y recomendaciones de enmiendas. Laboratorio propio.',
    rating: 4.9,
    jobs_completed: 203,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-5',
    display_name: 'Roberto Fernández',
    country: 'México',
    specialty: 'Riego',
    description: 'Diseño e instalación de sistemas de riego por goteo y aspersión. Certificado en agricultura de precisión.',
    rating: 4.6,
    jobs_completed: 42,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-6',
    display_name: 'Olena Kovalenko',
    country: 'Україна',
    specialty: 'Siembra',
    description: 'Operadora de sembradoras de precisión. Especialista en siembra directa de trigo y girasol.',
    rating: 4.8,
    jobs_completed: 68,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-7',
    display_name: 'James Mitchell',
    country: 'Australia',
    specialty: 'Ganadería',
    description: 'Veterinario rural con experiencia en manejo de ganado bovino y ovino. Especialista en nutrición animal.',
    rating: 4.7,
    jobs_completed: 91,
    verified_kyc: false,
    plan: 'free',
    seed: true,
  },
  {
    id: 'seed-8',
    display_name: 'Ana Rodrigues',
    country: 'Portugal',
    specialty: 'Consultoría',
    description: 'Consultora agrícola con máster en agricultura sostenible. Especializada en transición ecológica y certificaciones bio.',
    rating: 4.9,
    jobs_completed: 156,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-9',
    display_name: 'Raj Patel',
    country: 'India',
    specialty: 'Fumigación',
    description: 'Técnico en protección de cultivos con certificación en manejo integrado de plagas. Experiencia en arroz y algodón.',
    rating: 4.5,
    jobs_completed: 34,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-10',
    display_name: 'Lucas Moretti',
    country: 'Argentina',
    specialty: 'Topografía',
    description: 'Agrimensor con equipos RTK de última generación. Relevamientos, nivelación y diseño de sistematización.',
    rating: 4.8,
    jobs_completed: 73,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-11',
    display_name: 'Isabella Torres',
    country: 'México',
    specialty: 'Drones Agrícolas',
    description: 'Ingeniera en geomática. Mapeo multiespectral, NDVI y detección temprana de estrés hídrico con drones.',
    rating: 4.7,
    jobs_completed: 45,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-12',
    display_name: 'Miguel Ángel Ruiz',
    country: 'España',
    specialty: 'Arado',
    description: 'Operador de maquinaria pesada. Subsolado, chisel y arado de vertedera. Flota propia de tractores 300+ CV.',
    rating: 4.6,
    jobs_completed: 189,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-13',
    display_name: 'Carlos Martínez Herrera',
    country: 'España',
    specialty: 'Riego',
    description: 'Ingeniero de riego con 12 años de experiencia en olivar y almendro. Diseño de sistemas de goteo, aspersión y fertirrigación automatizada en Andalucía.',
    rating: 4.9,
    jobs_completed: 145,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-14',
    display_name: 'Laura Sánchez Moreno',
    country: 'España',
    specialty: 'Drones Agrícolas',
    description: 'Piloto de drones certificada por AESA. Fumigación de precisión, mapeo NDVI y detección de estrés hídrico en viñedos y frutales en Castilla-La Mancha.',
    rating: 4.8,
    jobs_completed: 67,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-15',
    display_name: 'Javier Fernández Ortega',
    country: 'España',
    specialty: 'Topografía',
    description: 'Topógrafo con equipos GPS RTK y estación total. Levantamientos, nivelaciones y proyectos de sistematización para regadío en Aragón y Cataluña.',
    rating: 4.7,
    jobs_completed: 98,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-16',
    display_name: 'Ana Rodríguez Vega',
    country: 'España',
    specialty: 'Análisis de Suelo',
    description: 'Ingeniera agrónoma con laboratorio propio en Valencia. Análisis físico-químico, microbiológico y planes de abonado personalizados para cítricos y hortalizas.',
    rating: 4.9,
    jobs_completed: 210,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-17',
    display_name: 'Pedro Navarro Gil',
    country: 'España',
    specialty: 'Cosecha',
    description: 'Operador de cosechadoras con flota propia (3 cosechadoras New Holland). Servicio de cosecha de cereal en Castilla y León con sistema de medición por GPS.',
    rating: 4.6,
    jobs_completed: 178,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-18',
    display_name: 'Isabel Torres Muñoz',
    country: 'España',
    specialty: 'Ganadería',
    description: 'Veterinaria rural especializada en ganado ibérico y ovino. Planes sanitarios, nutrición y mejora genética en dehesas de Extremadura.',
    rating: 4.8,
    jobs_completed: 132,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-19',
    display_name: 'Francisco López Castillo',
    country: 'España',
    specialty: 'Fumigación',
    description: 'Técnico en aplicación de fitosanitarios con carnet de manipulador. Tratamientos terrestres en olivar, viñedo y cereales en Andalucía y Castilla-La Mancha.',
    rating: 4.5,
    jobs_completed: 89,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-20',
    display_name: 'Carmen Díaz Romero',
    country: 'España',
    specialty: 'Consultoría',
    description: 'Consultora agrícola con máster en agricultura de precisión. Asesoramiento en PAC, certificaciones ecológicas y transición sostenible en Andalucía.',
    rating: 4.9,
    jobs_completed: 167,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-21',
    display_name: 'Antonio Gómez Serrano',
    country: 'España',
    specialty: 'Siembra',
    description: 'Especialista en siembra directa y agricultura de conservación. Sembradoras de precisión con GPS para cereal y girasol en Castilla-La Mancha.',
    rating: 4.7,
    jobs_completed: 95,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-22',
    display_name: 'Elena Martín Blanco',
    country: 'España',
    specialty: 'Poda',
    description: 'Experta en poda de formación y producción de almendro y olivar superintensivo. Equipos mecanizados y manuales. Trabaja en Murcia y Almería.',
    rating: 4.8,
    jobs_completed: 156,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
  {
    id: 'seed-23',
    display_name: 'David Ruiz Peña',
    country: 'España',
    specialty: 'Transporte',
    description: 'Empresa de transporte agrícola con flota de 8 camiones. Transporte de cereal, aceituna y uva en toda España. Servicio 24h en campaña.',
    rating: 4.6,
    jobs_completed: 234,
    verified_kyc: true,
    plan: 'enterprise',
    seed: true,
  },
  {
    id: 'seed-24',
    display_name: 'Sofía Hernández Rivas',
    country: 'España',
    specialty: 'Drones Agrícolas',
    description: 'Ingeniera agrónoma y piloto de drones. Monitoreo de cultivos con cámaras multiespectrales y térmicas. Detección temprana de plagas en frutales en Lleida.',
    rating: 4.8,
    jobs_completed: 54,
    verified_kyc: true,
    plan: 'pro',
    seed: true,
  },
];

export const SEED_JOBS = [
  {
    id: 'seed-job-1',
    title: 'Fumigación aérea con drones para 800 hectáreas de soja',
    description: 'Necesito servicio de fumigación aérea con drones para aplicación de herbicida preemergente en 800 hectáreas de soja. La parcela está en la zona de Pergamino. Se requiere equipo con capacidad mínima de 20L y certificación ANAC.',
    category: 'Drones Agrícolas',
    country: 'Argentina',
    location: 'Pergamino, Buenos Aires',
    hectares: 800,
    budget_min: 4500,
    budget_max: 7000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-2',
    title: 'Poda de 3.000 olivos en finca de Jaén',
    description: 'Buscamos equipo de podadores profesionales para poda de producción en olivar intensivo. 3.000 árboles variedad Picual. Acceso con maquinaria posible. Plazo: enero-febrero.',
    category: 'Poda',
    country: 'España',
    location: 'Jaén, Andalucía',
    hectares: 45,
    budget_min: 8000,
    budget_max: 12000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-3',
    title: 'Cosecha mecanizada de 2.000 ha de maíz en Mato Grosso',
    description: 'Requiero servicio de cosecha mecanizada para segunda safra de maíz. Área total 2.000 hectáreas. Se necesitan mínimo 3 cosechadoras con plataforma de 12 surcos. Logística de transporte incluida.',
    category: 'Cosecha',
    country: 'Brasil',
    location: 'Sorriso, Mato Grosso',
    hectares: 2000,
    budget_min: 35000,
    budget_max: 50000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-4',
    title: 'Instalación de riego por goteo en 50 hectáreas de aguacate',
    description: 'Proyecto de instalación completa de sistema de riego por goteo para plantación nueva de aguacate Hass. Incluye diseño hidráulico, cabezal de filtrado, tuberías principales y laterales con goteros autocompensantes.',
    category: 'Riego',
    country: 'México',
    location: 'Uruapan, Michoacán',
    hectares: 50,
    budget_min: 15000,
    budget_max: 22000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-5',
    title: 'Análisis completo de suelo para 200 ha de viñedo',
    description: 'Necesito análisis de suelo completo (físico, químico y biológico) con muestreo georreferenciado cada 2 hectáreas. Incluir mapa de variabilidad y recomendaciones de enmiendas para viñedo de calidad.',
    category: 'Análisis de Suelo',
    country: 'France',
    location: 'Burdeos, Gironde',
    hectares: 200,
    budget_min: 6000,
    budget_max: 9000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-6',
    title: 'Siembra directa de trigo en 1.500 hectáreas',
    description: 'Servicio de siembra directa de trigo sobre rastrojo de girasol. 1.500 hectáreas en zona de Odessa. Se requiere sembradora de precisión con fertilización en línea. Semilla y fertilizante los proveo yo.',
    category: 'Siembra',
    country: 'Україна',
    location: 'Odessa Oblast',
    hectares: 1500,
    budget_min: 12000,
    budget_max: 18000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-7',
    title: 'Consultoría para transición a agricultura ecológica',
    description: 'Busco consultor agrícola para acompañar la transición de 120 hectáreas de cultivos extensivos a producción ecológica certificada. Necesito plan de conversión, rotaciones y asesoramiento en certificación EU Organic.',
    category: 'Consultoría',
    country: 'Portugal',
    location: 'Alentejo',
    hectares: 120,
    budget_min: 5000,
    budget_max: 8000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-8',
    title: 'Relevamiento topográfico y sistematización de 300 ha',
    description: 'Necesito relevamiento altimétrico con GPS RTK y proyecto de sistematización para drenaje y riego gravitacional. 300 hectáreas en zona baja con problemas de anegamiento.',
    category: 'Topografía',
    country: 'Argentina',
    location: 'Venado Tuerto, Santa Fe',
    hectares: 300,
    budget_min: 4000,
    budget_max: 6500,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-9',
    title: 'Instalación de riego por goteo en olivar - Jaén',
    description: 'Necesito instalar un sistema de riego por goteo en una finca de olivar de 45 hectáreas en la provincia de Jaén. El terreno tiene pendiente moderada y necesita estudio previo de caudal disponible. Preferiblemente profesional con experiencia en olivar intensivo.',
    category: 'Riego',
    country: 'España',
    location: 'Jaén, Andalucía',
    hectares: 45,
    budget_min: 8000,
    budget_max: 15000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-10',
    title: 'Fumigación con drones en viñedo - La Rioja',
    description: 'Busco servicio de fumigación aérea con drones para viñedo de 30 hectáreas en La Rioja. Tratamiento preventivo contra mildiu y oídio. Se requiere certificación oficial de operador de drones y productos fitosanitarios ecológicos.',
    category: 'Drones Agrícolas',
    country: 'España',
    location: 'Haro, La Rioja',
    hectares: 30,
    budget_min: 3000,
    budget_max: 5500,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-11',
    title: 'Análisis completo de suelos para cítricos - Valencia',
    description: 'Requiero análisis completo de suelos para una finca de cítricos de 20 hectáreas en Valencia. Necesito análisis físico-químico, microbiológico y plan de abonado personalizado para naranjos y mandarinos.',
    category: 'Análisis de Suelo',
    country: 'España',
    location: 'Alzira, Valencia',
    hectares: 20,
    budget_min: 2000,
    budget_max: 4000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-12',
    title: 'Cosecha mecanizada de cereal - Valladolid',
    description: 'Necesito servicio de cosecha mecanizada para 200 hectáreas de trigo y cebada en la provincia de Valladolid. Campaña de julio. Se requiere cosechadora con sistema de medición de rendimiento por GPS.',
    category: 'Cosecha',
    country: 'España',
    location: 'Medina del Campo, Valladolid',
    hectares: 200,
    budget_min: 12000,
    budget_max: 20000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-13',
    title: 'Poda de olivar superintensivo en seto - Córdoba',
    description: 'Busco equipo de poda para olivar superintensivo en seto de 60 hectáreas en Córdoba. Poda de formación y producción. Experiencia demostrable en olivar en seto (Arbequina y Picual).',
    category: 'Poda',
    country: 'España',
    location: 'Lucena, Córdoba',
    hectares: 60,
    budget_min: 5000,
    budget_max: 9000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-14',
    title: 'Consultoría ganadera en dehesa - Extremadura',
    description: 'Busco consultor especializado en ganadería extensiva para optimizar el manejo de una dehesa de 150 hectáreas con ganado ibérico en Cáceres. Incluye plan de rotación de pastos y mejora genética del rebaño.',
    category: 'Ganadería',
    country: 'España',
    location: 'Trujillo, Cáceres',
    hectares: 150,
    budget_min: 3000,
    budget_max: 6000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-15',
    title: 'Topografía y nivelación de parcelas de regadío - Huesca',
    description: 'Necesito levantamiento topográfico y proyecto de nivelación para 80 hectáreas de regadío en Huesca. Preparación para transformación a riego por aspersión. Se requiere informe técnico completo.',
    category: 'Topografía',
    country: 'España',
    location: 'Monzón, Huesca',
    hectares: 80,
    budget_min: 4000,
    budget_max: 7000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-16',
    title: 'Siembra directa de girasol - Ciudad Real',
    description: 'Busco servicio de siembra directa para 100 hectáreas de girasol en Ciudad Real. Se requiere sembradora de precisión con GPS y experiencia en siembra directa sobre rastrojo de cereal.',
    category: 'Siembra',
    country: 'España',
    location: 'Manzanares, Ciudad Real',
    hectares: 100,
    budget_min: 5000,
    budget_max: 8000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-17',
    title: 'Plan de fertilización para almendro - Murcia',
    description: 'Necesito un plan de fertilización completo para una plantación de almendro de 35 hectáreas en Murcia. Variedades Guara y Lauranne en regadío. Incluir fertirrigación y enmiendas orgánicas.',
    category: 'Consultoría',
    country: 'España',
    location: 'Cieza, Murcia',
    hectares: 35,
    budget_min: 2500,
    budget_max: 4500,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-18',
    title: 'Diseño de riego hidropónico para invernadero - Almería',
    description: 'Proyecto de diseño e instalación de sistema de riego hidropónico para invernadero de 5 hectáreas de tomate en Almería. Sistema NFT con control automatizado de nutrientes y pH.',
    category: 'Riego',
    country: 'España',
    location: 'El Ejido, Almería',
    hectares: 5,
    budget_min: 15000,
    budget_max: 25000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-19',
    title: 'Fumigación terrestre en cereal - Zamora',
    description: 'Necesito tratamiento fitosanitario terrestre para 150 hectáreas de trigo blando en Zamora. Aplicación de fungicida en espigado. Se requiere pulverizador autopropulsado con barra de 36m mínimo.',
    category: 'Fumigación',
    country: 'España',
    location: 'Toro, Zamora',
    hectares: 150,
    budget_min: 3500,
    budget_max: 5000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-20',
    title: 'Transporte de aceituna a almazara - Córdoba',
    description: 'Servicio de transporte de aceituna desde finca hasta almazara durante campaña de recolección (noviembre-enero). Estimación de 500 toneladas. Distancia 25km. Se requieren remolques de 12t.',
    category: 'Transporte',
    country: 'España',
    location: 'Baena, Córdoba',
    hectares: 80,
    budget_min: 4000,
    budget_max: 6000,
    contract_type: 'reverse_auction',
    status: 'open',
    seed: true,
  },
  {
    id: 'seed-job-21',
    title: 'Arado y preparación de suelo para viñedo - Ribera del Duero',
    description: 'Necesito servicio de subsolado y preparación de suelo para nueva plantación de viñedo de 25 hectáreas en Ribera del Duero. Incluye subsolado a 80cm, pase de cultivador y nivelación.',
    category: 'Arado',
    country: 'España',
    location: 'Aranda de Duero, Burgos',
    hectares: 25,
    budget_min: 6000,
    budget_max: 9000,
    contract_type: 'fixed_price',
    status: 'open',
    seed: true,
  },
];